# Generated by Django 5.0.6 on 2026-05-26 02:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_match',
                'indexes': [models.Index(fields=['user_1', 'is_active'], name='matches_mat_user_1__b6d298_idx'), models.Index(fields=['user_2', 'is_active'], name='matches_mat_user_2__a96f00_idx')],
                'unique_together': {('user_1', 'user_2')},
            },
        ),
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('like', 'Like'), ('superlike', 'Super Like'), ('pass', 'Pasar')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_given', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches_swipe',
                'indexes': [models.Index(fields=['user_from', 'action'], name='matches_swi_user_fr_64f756_idx'), models.Index(fields=['user_to', 'action'], name='matches_swi_user_to_faff1b_idx')],
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
