# Generated by Django 5.0.6 on 2026-05-26 02:29

import apps.verification.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula_number', models.CharField(blank=True, max_length=20)),
                ('cedula_front', models.ImageField(blank=True, null=True, upload_to=apps.verification.models.document_upload_path)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=apps.verification.models.selfie_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('verified', 'Verificado'), ('rejected', 'Rechazado'), ('manual_review', 'Revisión manual')], default='pending', max_length=20)),
                ('ocr_raw', models.JSONField(blank=True, default=dict)),
                ('ocr_cedula_extracted', models.CharField(blank=True, max_length=20)),
                ('ocr_name_extracted', models.CharField(blank=True, max_length=200)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('cedula_valid_format', models.BooleanField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de identidad',
                'verbose_name_plural': 'Verificaciones de identidad',
                'db_table': 'verification_identity',
            },
        ),
    ]
