# Generated by Django 5.0.6 on 2026-05-26 02:28

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'users_interest',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('NB', 'No binario'), ('O', 'Otro')], max_length=5)),
                ('orientation', models.CharField(choices=[('straight', 'Heterosexual'), ('gay', 'Gay/Lesbiana'), ('bisexual', 'Bisexual'), ('other', 'Otro')], default='straight', max_length=15)),
                ('looking_for', models.CharField(choices=[('serious', 'Algo serio'), ('casual', 'Citas casuales'), ('friends', 'Amistades'), ('any', 'Cualquier cosa')], default='any', max_length=15)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Colombia', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_photo_upload)),
                ('min_age_preference', models.IntegerField(default=18)),
                ('max_age_preference', models.IntegerField(default=45)),
                ('max_distance_km', models.IntegerField(default=50)),
                ('show_gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('NB', 'No binario'), ('O', 'Otro'), ('A', 'Todos')], default='A', max_length=5)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='users.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'users_profile',
            },
        ),
    ]
